try{
    console.log(rahul);
} catch(err){
    console.log("Error is occured " +err)
}